projects:
  sampleapp:
    schemaPath: src/graphql/schema.json
    includes:
      - 'Y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
